server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.31:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: kairong
    password: kaironG@123

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
